export default [
    {
        ignores: ["node_modules/**"],
        files: ["**/*.js"],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "module",
            globals: {
                Array: "readonly",
                Boolean: "readonly",
                Date: "readonly",
                Error: "readonly",
                JSON: "readonly",
                Map: "readonly",
                Math: "readonly",
                Number: "readonly",
                Object: "readonly",
                Promise: "readonly",
                Set: "readonly",
                String: "readonly",
                TextDecoder: "readonly",
                Uint8Array: "readonly",
                URL: "readonly",
                atob: "readonly",
                chrome: "readonly",
                clearTimeout: "readonly",
                console: "readonly",
                document: "readonly",
                setTimeout: "readonly",
                test: "readonly",
                assert: "readonly",
                process: "readonly",
            },
        },
        rules: {
            "no-undef": "error",
            "no-unused-vars": ["error", { "args": "after-used" }],
            "no-var": "error",
        },
    },
];
